#CLOVA TUNNING MODEL
API_KEY = "<<이곳에 API_KEY 입력>>"
API_KEY_PRIMAL_VAL = "<<이곳에 API_KEY_PRIMAL_VAL 입력>>"

#CLOVA TTS/EMOTION
CLIENT_ID = "<<이곳에 CLIENT_ID 입력>>"
CLIENT_SECRET = "<<이곳에 CLIENT_SECRET 입력>>"